### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#115]
- build and publish  a conda package
- publish on conda-forge?

older comment: follow examples from [spec2nexus](https://github.com/prjemian/spec2nexus/tree/master/conda-recipe), [pyRestTable](https://github.com/prjemian/pyRestTable/tree/master/conda-recipe), and [apstools](https://github.com/BCDA-APS/apstools/tree/master/conda-recipe)

https://github.com/conda-forge/punx-feedstock

**Comment by prjemian** [comment]
https://github.com/BEFH/anaconda-publish

**Comment by carterbox** [comment]
There's already a conda-forge package for punx. I assume that this issue is just to remind us rebuild that feedstock when v1 is released?

**Comment by prjemian** [comment]
You are correct.  The [feedstock was built](https://github.com/conda-forge/punx-feedstock/graphs/contributors) by Maksim Rakitin (at NSLS-II).  I need to understand it.

**Comment by prjemian** [comment]
Will make a new tag and see how to proceed with the conda-forge feedstock.  I assume the automation will recognize a new tag and generate a new PR for the feedstock which must be reviewed before the conda package is posted.

**Comment by carterbox** [comment]
Actually, it looks like "automerge" is setup for that feedstock, so human intervention for the feedstock is only needed if the tests in the recipe section fail.

**Comment by prjemian** [comment]
Agreed, it is working.
