### ISSUE TITLE
refactor README to markdown and update badging

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#138]
The repo's README can be refactored to markdown.  The badging needs an update as well, since various tools have been swapped.

**Comment by prjemian** [comment]
Should not have been closed in #145.

**Comment by prjemian** [comment]
@carterbox - This is easy.  But the docs include the `README.rst` directly.  A new page should be created in the docs separate from the refactored `README.md`.

**Comment by carterbox** [comment]
Why do you want to duplicate your docs? What's the problem with using the RST for both README and docs landing page?

**Comment by prjemian** [comment]
The project README file has similar but slightly different purposes than similar content int he documentation.

Here's why I am tending to separate these now.  As in other projects, it becomes cumbersome to continue rendering some content (such as badges) in the documentation.  With badges, they are often updated _after_ the online docs have been recreated.  Continuing to use the project README in the published documentation limits the formatting options for both the project README and the published documentation.

**Comment by carterbox** [comment]
My understanding is that you don't want broken badges on your archived (non-latest/stable) version of the docs, so you have separated the landing pages and only have badges only on the GitHub landing. Makes sense.

But what changes besides removing the Depsy badge (the only broken badge) do you want to this landing page? Removing the Depsy badge does not require swapping from RST to MD. There should be a something else that you want which is enabled by switching to MD?

**Comment by prjemian** [comment]
> (such as badges)

which means that _other_ maintenance becomes easier.  It has become tiresome trying to make this page work both in the documentation (as `.rst`) and as the project description page in the GitHub repository.  It is not necessary to make these two use cases render the exact same information.

**Comment by prjemian** [comment]
Wait for PR #154 to be merged before proceeding, other wise a merge conflict will exist.

**Comment by prjemian** [comment]
```bash
(bluesky_2022_1) prjemian@zap:~/.../prjemian/punx$ git grep README
MANIFEST.in:include README.rst
setup.cfg:description-file = README.rst
setup.py:README = os.path.join(os.path.dirname(__file__), "README.rst")
setup.py:long_description = open(README, "r").read()
```

**Comment by prjemian** [comment]
So, the README is not currently used in the documentation.

**Comment by prjemian** [comment]
The `long_description` appears on PyPI, for example.  In the [`pvview` project](https://github.com/BCDA-APS/pvview/blob/431fcb64a6422beb1d801f7fd62fb4a77cc8b18b/setup.py#L16), the README is markdown:

    long_description = open('README.md', 'r').read()

but the [PyPI page](https://pypi.org/project/pvview/) displays the markup and this looks like an error.

**Comment by prjemian** [comment]
README page is still not very pretty but it is a direct translation (via [pandoc](https://pandoc.org/)).
