### ISSUE TITLE
--report option of punx validate is broken?

### ISSUE THREAD

**Issue by carterbox** [prjemian/punx#158]
```
punx validate --report ERROR punx/data/1998spheres.h5
```
The above command should restrict the report to only showing ERROR status findings? Instead it shows all findings.

Could use:
```
punx validate punx/data/1998spheres.h5 | grep ERROR
```
but then why is there a --report option?

**Comment by prjemian** [comment]
RIght.  Can use `grep` to filter results.  The `--report` option controls the _level_ of finding statuses that are reported.  `COMMENT,ERROR,NOTE,OK,OPTIONAL,TODO,UNUSED,WARN`

Time to revise the handling of this feature.

**Comment by prjemian** [comment]
On Windows, it is harder to expect the `grep` command is available and that users know how pipe commands together.
