### ISSUE TITLE
pip installation missing dependencies

### ISSUE THREAD

**Issue by DanPorter** [prjemian/punx#249]
Hi, I've just been trying out punx to validate some new NeXus files at Diamond.

I've noticed that if I install punx in a fresh environment using pip, it does not install any of the dependencies:
```bash
$ conda create -n validateNexus python=3.12
$ conda activate validateNexus
(validateNexus) $ python -m pip install punx
(validateNexus) $ punx

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\Anaconda3\envs\validateNexus\Scripts\punx.exe\__main__.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\envs\validateNexus\Lib\site-packages\punx\main.py", line 65, in <module>
    from punx import cache_manager
  File "C:\ProgramData\Anaconda3\envs\validateNexus\Lib\site-packages\punx\cache_manager.py", line 68, in <module>
    import pyRestTable
ModuleNotFoundError: No module named 'pyRestTable'

(validateNexus) $ python -m pip show punx

show punx
Name: punx
Version: 0.3.4
Summary: Python Utilities for NeXus HDF5 files.
...
Requires:
(None)
```

Installation via conda-forge worked as expected:
```
(validateNexus) $ conda install -n validateNexus punx
(validateNexus) $ punx
```

To allow installation using pip, I think the solution will be to add the dependencies to the pyproject.toml file:
```
[project]
...
requires-python = ">=3.8"
dependencies = [
  "h5py",
  "hdf5plugin",
  "lxml",
  "numpy",
  "pyRestTable",
  "requests",
]
```
Possibly other dependencies are required as well - for some reason it seems to want to install PyQt - this seems a very large package to install if I am only going to use the CLI.

**Comment by prjemian** [comment]
Thanks for that report.  You're right that `dependencies` is missing.  They were missed when updating to `pyproject.toml` packaging.  Here they were in a previous release: https://github.com/prjemian/punx/blob/af8eefc5b2dc65af7739fb0fee65d917126fbf1e/punx/__init__.py#L66-L75

The entirety of PyQt5 (now) is not needed, certainly not the GUI parts, only `QtCore` for its [QSettings](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QSettings.html):

https://github.com/prjemian/punx/blob/f24c79cdfdb902c556dee02857ec6aa73c8b4066/punx/cache_manager.py#L72

https://github.com/prjemian/punx/blob/f24c79cdfdb902c556dee02857ec6aa73c8b4066/punx/cache_manager.py#L451-L453

**Comment by prjemian** [comment]
With these changes, this procedure works:

```bash
(base) $ conda create -y -n test "python=3.12"
(test) $ conda activate test
(test) $ python -m pip install -e .
(test) $ punx -v
```
